# This is the configuration for our GitHub Actions workflow.
# The workflow is triggered on push and pull request events targeting the main branch.
name: My Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/jobs.yml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/jobs.yml'
  workflow_dispatch:

jobs:
    # Job 1 runs first
    job1:
        runs-on: ubuntu-latest
        steps:
        # Step to checkout the code from the repository
        - name: Checkout code
          uses: actions/checkout@v2
        # Step to run a simple script
        - name: Run a script
          run: echo "Hello, world!"
    # Job 2 depends on the successful completion of Job 1
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
        # Step to checkout the code from the repository
        - name: Checkout code
          uses: actions/checkout@v2
        # Step to run another simple script
        - name: Run another script
          run: echo "Hello, again!"
